// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://futioilrogbfwpgyqlqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1dGlvaWxyb2diZndwZ3lxbHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDUwOTQsImV4cCI6MjA2NjYyMTA5NH0.-aWlZ_b-8Uavn_VrF4GqsElVoQ_061b6xnLDUwIGhoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);